<a href="https://colab.research.google.com/github/yuja1130/AIpython./blob/main/20240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
# 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열 생성
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
# 모양이 (3,4)인 모든 값이 1인 배열
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# 0과 1 사이를 10등분하고자 할 때 등분값 배열 생성
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
# A행렬 생성
A = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20],[21,22,23,24,25]])
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
# A의 모양(shape) 출력
A.shape

(5, 5)

In [29]:
# 19 값 출력
A[3,3]

19

In [31]:
# 슬라이싱 이용 -> [[1,2], [6,7]] 값 추출
A[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [23]:
# 슬라이싱 이용 -> [[19,20], [24,25]] 값 추출
A[3:5, 3:5]

array([[19, 20],
       [24, 25]])

In [34]:
# 슬라이싱 이용 -> 0축의 첫 번째 행, 두 번째 행 추출
A[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
# 슬라이싱 이용 -> 1축의 마지막 열, 마지막 직전 열 추출
A[ : , 3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [39]:
# B 행렬 생성
B = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[13,14,15,16], [17,18,19,20], [21,22,23,24]], [[25,26,27,28],[29,30,31,32], [33,34,35,36]]])
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [46]:
B = np.arange(1,37).reshape(3,3,4)
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [41]:
# B 배열의 모양과 크기 출력
B.shape

(3, 3, 4)

In [42]:
B.size

36

In [43]:
# B의 모양을 (3,4,3)로 변경
B.reshape(3,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [44]:
# B를 1차원 배열로 구성
B.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])